### ISSUE TITLE
Inquiry Regarding Causal Graph Construction for KGE Tasks

### ISSUE THREAD

**Issue by Sakhaa-Alsaedi** [zjukg/CausE#1]
Hello,

I am interested in exploring the code responsible for checking the Sufficient Markov Condition (SMC) for Knowledge Graph Embedding (KGE) tasks. Could you please direct me to the specific part of this repository where I can find the code related to checking the causal graph structure? Any guidance towards the relevant Python file or section that illustrates this aspect would be greatly appreciated.

Thank you.

**Comment by Zhang-Each** [comment]
The main implementation of the model is in openke/module/model/CDKGE.py, and we design a causal model and a confounder model in it. The code implementation is an approximation of our method formally described in our paper.
