### ISSUE TITLE
Inquiry Regarding Preparing Data for CauseE with OpenKE Format

### ISSUE THREAD

**Issue by Sakhaa-Alsaedi** [zjukg/CausE#2]
Hello,

I'm looking to implement CauseE for my knowledge graph project. I've already prepared my knowledge graph triple data using PyKEEN's TripleFactory and then converted it to match the OpenKE format, resulting in three files (entity2id.txt, relation2id.txt, and  train2id.txt). However, I noticed an "n-n.py" file within the benchmark data. My question is: Is it necessary to run this "n-n.py" file to utilize CauseE effectively, or is it possible to proceed with using CauseE without this step?

Thank you

**Comment by Zhang-Each** [comment]
Yes, running n-n.py is a must-done step if you want to create your own dataset.
