### ISSUE TITLE
代码缺失

### ISSUE THREAD

**Issue by xiaocheng99** [zjukg/CausE#3]
您好 代码无法运行 在openke库中缺失 CDTransE等代码文件  可以提供一下代码吗？ 谢谢

**Comment by Zhang-Each** [comment]
你好，我们的模型代码实际上是CDKGE，CDTransE是早期版本单独用于TransE backbone的，在后续的更新中我们将这一部分代码删除了，你只需要将models目录下面的__init__.py文件中不存在的模型删除就可以正常运行代码。
